no_metadata = true
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 32
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
low_vram = false
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
learning_rate = 0.00001
loss_type = "l2"
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 200
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 6
max_grad_norm = 0.0
max_timestep = 1000
max_token_length = 75
min_bucket_reso = 512
min_snr_gamma = 5
mixed_precision = "bf16"
network_alpha = 16
network_args = ["conv_dim=4", "conv_alpha=4", "dropout=null"]
network_dim = 32
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Original"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False", "weight_decay=0.01",]
optimizer_type = "Adafactor"
output_dir = "/app/outputs"
output_name = "last"
pretrained_model_name_or_path = ""
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"
scale_weight_norms = 5
text_encoder_lr = 0.00001
train_batch_size = 4
train_data_dir = "img"
training_comment = ""
unet_lr = 0.00001
xformers = true
full_bf16 = true
max_train_epochs = 25
network_dropout = 0
caption_dropout_rate = 0.1
shuffle_caption = true
keep_tokens = 2
v_parameterization = false
train_text_encoder = true
adaptive_noise_scale = 0
persistent_data_loader_workers = true
sdpa = false
noise_offset = 0.0357
seed = 42